# movewin
bind=SUPER+CTRL,Up,movewin,+0,-20
bind=SUPER+CTRL,Down,movewin,+0,+20
bind=SUPER+CTRL,Left,movewin,-20,+0
bind=SUPER+CTRL,Right,movewin,+20,+0

# resizewin
bind=SUPER+ALT,Up,resizewin,+0,-20
bind=SUPER+ALT,Down,resizewin,+0,+20
bind=SUPER+ALT,Left,resizewin,-20,+0
bind=SUPER+ALT,Right,resizewin,+20,+0
