# switch layout
bind=SUPER,D,switch_layout
bind=SUPER+CTRL,T,setlayout,tile
bind=SUPER+CTRL,S,setlayout,scroller

# tile layout
bind=SUPER,T,incnmaster,1
bind=SUPER+SHIFT,T,incnmaster,-1

bind=SUPER,plus,setmfact +10
bind=SUPER,minus,setmfact -10

# scroller layout
bind=SUPER,R,switch_proportion_preset,
bind=SUPER+SHIFT,R,set_proportion,1.0

# gaps
bind=ALT+SHIFT,X,incgaps,1
bind=ALT+SHIFT,Z,incgaps,-1
bind=ALT+SHIFT,R,togglegaps
