bind=SUPER,M,togglemaximizescreen,
bind=SUPER+SHIFT,M,togglefullscreen,
bind=SUPER+CTRL,M,togglefakefullscreen,

# switch window status
bind=SUPER,I,minimized,
bind=SUPER+SHIFT,I,restore_minimized
bind=SUPER,Z,toggle_scratchpad

bind = SUPER,F,togglefloating
bind = SUPER,C,centerwin

bind=SUPER,Q,killclient,
bind=SUPER,G,toggleglobal,
