decoration {
	shadow {
		color = $primary
		color_inactive = $surface
	}
}

windowrule {
    name = color-floats
    match:float = true
    border_color = $secondary
    no_shadow = true
}

windowrule {
    name = pin-tiled
    match:tag = pinTiled
    border_color = $tertiary
    no_shadow = true
}
