#####################
### SUBMAP RESIZE ###
#####################

bindd = ALT, R, Entrar al Submapa Redimensionar, exec,   $submap +submapa
bindd = ALT, R, Entrar al Submapa Redimensionar, submap, resize

submap = resize

bindde = , right, Aumentar el Ancho de la Ventana[Submapa],  resizeactive, 10 0
bindde = , left,  Reducir el Ancho de la Ventana[Submapa],   resizeactive, -10 0
bindde = , up,    Aumentar la Altura de la Ventana[Submapa], resizeactive, 0 -10
bindde = , down,  Reducir la Altura de la Ventana[Submapa],  resizeactive, 0 10

bindd = , F1, Atajos de Hyprland, exec, $atajos submapa

bindd = , escape, Salir del Submapa, exec,   $submap submapa
bindd = , escape, Salir del Submapa, submap, reset

submap = reset
