"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

keymap = [
  # Plugin Mount
  { on = "M", run = "plugin mount", desc = "Discos" },

	{ on = "<Esc>", run = "escape --all --all", desc = "Salir del Modo Visual, Limpiar Selección, o Cancelar Busqueda" },
	{ on = "q",     run = "quit",               desc = "Salir" },
	{ on = "Q",     run = "quit --no-cwd-file", desc = "Salir sin Mantener Ruta" },
	{ on = "<C-c>", run = "close",              desc = "Cerrar Pestaña, ó Salir si es Única Pestaña" },
	{ on = "<C-z>", run = "suspend",            desc = "Suspender el Proceso" },

	# Hopping
	{ on = "k", run = "arrow prev", desc = "Regresar Anterior Archivo" },
	{ on = "j", run = "arrow next", desc = "Ir Siguente Archivo" },

	{ on = "<Up>",   run = "arrow prev", desc = "Regresar Anterior Archivo" },
	{ on = "<Down>", run = "arrow next", desc = "Ir Siguente Archivo" },

	{ on = "<C-u>", run = "arrow -50%",  desc = "Mover el Cursor Media Pagina Arriba" },
	{ on = "<C-d>", run = "arrow 50%",   desc = "Mover el Cursor Media Pagina Abajo" },
	{ on = "<C-b>", run = "arrow -100%", desc = "Mover el Cursor Una Pagina Arriba" },
	{ on = "<C-f>", run = "arrow 100%",  desc = "Mover el Cursor Una Pagina Abajo" },

	{ on = [ "g", "g" ], run = "arrow top", desc = "Ir Inicio del Directorio" },
	{ on = [ "g", "e" ], run = "arrow bot", desc = "Ir Final del Directorio" },

	# Navigation
	{ on = "h", run = "leave", desc = "Salir del Directorio" },
	{ on = "l", run = "enter", desc = "Entrar al Directorio" },

	{ on = "<Left>",  run = "leave", desc = "Salir del Directorio" },
	{ on = "<Right>", run = "enter", desc = "Entrar al Directorio" },

	{ on = "H", run = "back",    desc = "Regresar al Anterior Directorio" },
	{ on = "L", run = "forward", desc = "Ir al Último Directorio" },

	# Toggle
	{ on = "<Space>",   run = [ "toggle", "arrow 1" ],  desc = "Seleccionar hacia al Siguiente" },
	{ on = "<C-Space>", run = [ "toggle", "arrow -1" ], desc = "Seleccionar hacia al Anterior" },
	{ on = "<C-a>",     run = "toggle_all --state=on",  desc = "Seleccionar Todo" },
	{ on = "<C-r>",     run = "toggle_all",             desc = "Invertir Selección" },

	# Visual mode
	{ on = "v", run = "visual_mode",         desc = "Entrar en el Modo Visual (Modo Selección)" },
	{ on = "V", run = "visual_mode --unset", desc = "Entrar en el Modo Visual (Modo Deselecionar)" },

	# Seeking
# Búsqueda (Seek)
{ on = "K", run = "seek -5", desc = "Desplazar 5 Filas hacia Arriba en la Vista Previa" },
{ on = "J", run = "seek 5",  desc = "Desplazar 5 Filas hacia Abajo en la Vista Previa" },

{ on = "<C-up>",   run = "seek -5", desc = "Desplazar 5 Filas hacia Arriba en la Vista Previa" },
{ on = "<C-down>", run = "seek 5",  desc = "Desplazar 5 Filas hacia Abajo en la Vista Previa" },

	# Spotting
	{ on = "<Tab>", run = "spot", desc = "Propiedades del Archivo Seleccionado" },

	# Operation
	{ on = "o",         run = "open",               desc = "Abrir Archivo Seleccionado" },
	{ on = "O",         run = "open --interactive", desc = "Elegir donde Abrir el Archivo Seleccionado" },
	{ on = "<Enter>",   run = "open --interactive", desc = "Abrir Archivo Seleccionado" },
	{ on = "<C-Enter>", run = "open",               desc = "Elegir donde Abrir el Archivo Seleccionado" },

	{ on = "y", run = "yank",          desc = "Copiar Archivos Seleccionados" },
	{ on = "x", run = "yank --cut",    desc = "Cortar Archivos Seleccionados" },
	{ on = "p", run = "paste",         desc = "Pegar Archivos Seleccionados" },
  { on = "P", run = "paste --force", desc = "Pegar Archivos Seleccionados (Sobrescribir SI el Destino Existe)" },
  { on = "Y", run = "unyank",        desc = "Cancelar Selección" },
  { on = "X", run = "unyank",        desc = "Cancelar Selección" },

  { on = "d", run = "remove",               desc = "Enviar el(los) Archivo(s) Seleccionado(s) a la Papelera" },
  { on = "D", run = "remove --permanently", desc = "Eliminar Permanentemente el(los) Archivos Seleccionados" },

  { on = "a", run = "create",       desc = "Crear un Archivo (Si Termina en / es para Crear un Directorio)" },
  { on = "A", run = "create --dir", desc = "Crear un Directorio" },

  { on = "r", run = "rename --empty=stem --cursor=start", desc = "Renombrar Archivo(s) Seleccionado(s)" },
  { on = "R", run = "rename --cursor=before_ext",         desc = "Renombrar Archivo(s) Seleccionado(s)" },

  { on = ";",         run = "shell --interactive",         desc = "Ejecutar un Comando de SHELL" },
  { on = ":",         run = "shell --block --interactive", desc = "Ejecutar un Comando de SHELL (Bloquea hasta que Termine)" },

  { on = [ "s", "f", ], run = "search --via=fd", desc = "Buscar Archivos por Nombre usando fd" },
  { on = [ "s", "r", ], run = "search --via=rg", desc = "Buscar Archivos por Contenido usando ripgrep" },
  { on = [ "s", "c", ], run = "escape --search", desc = "Cancelar la Búsqueda en Curso" },
  { on = "z",           run = "plugin fzf",      desc = "Saltar a un Archivo o Carpeta usando fzf" },
  { on = "Z",           run = "plugin zoxide",   desc = "Saltar a una Carpeta usando zoxide" },

  { on = ".", run = "hidden toggle",   desc = "Mostrar u Ocultar Archivos Ocultos" },

  { on = "-",     run = "link",            desc = "Crear Enlace Simbólico con la Ruta Absoluta de los Archivos Seleccionados" },
  { on = "_",     run = "link --relative", desc = "Crear Enlace Simbólico con la Ruta Relativa de los Archivos Seleccionados" },
  { on = "<C-->", run = "hardlink",        desc = "Crear Hardlink de los Archivos Seleccionados" },

	# Linemode
  { on = [ "m", "s" ], run = "linemode size",           desc = "Información: Tamaño" },
  { on = [ "m", "p" ], run = "linemode permissions",    desc = "Información: Permisos" },
  { on = [ "m", "b" ], run = "linemode btime",          desc = "Información: Fecha de Creación" },
  { on = [ "m", "m" ], run = "linemode mtime",          desc = "Información: Fecha de Modificación" },
  { on = [ "m", "o" ], run = "linemode owner",          desc = "Información: Propietario" },
  { on = [ "m", "n" ], run = "linemode none",           desc = "Información: Ninguno" },
  { on = [ "m", "t" ], run = "linemode size_and_mtime", desc = "Información: Tamaño y Fecha de Creación" },

	# Copy
  { on = [ "c", "c" ], run = "copy path --separator=unix",             desc = "Copiar la Ruta del Archivo" },
  { on = [ "c", "d" ], run = "copy dirname --separator=unix",          desc = "Copiar la Ruta del Directorio" },
  { on = [ "c", "f" ], run = "copy filename --separator=unix",         desc = "Copiar el Nombre del Archivo" },
  { on = [ "c", "n" ], run = "copy name_without_ext --separator=unix", desc = "Copiar el Nombre del Archivo sin Extensión" },

	# Filter
	{ on = "f", run = "filter --smart", desc = "Filtrar Archivos" },

	# Find
	{ on = "/", run = "find --smart",            desc = "Buscar Archivo Siguente " },
	{ on = "?", run = "find --previous --smart", desc = "Buscar Archivo Anterior" },
	{ on = "n", run = "find_arrow",              desc = "Siguente Encontrado" },
	{ on = "N", run = "find_arrow --previous",   desc = "Anterior Encontrado" },

	# Sorting
	{ on = [ ",", "m" ], run = [ "sort mtime --reverse=no", "linemode mtime" ], desc = "Ordenar por Fecha de Modificación" },
	{ on = [ ",", "M" ], run = [ "sort mtime --reverse", "linemode mtime" ],    desc = "Ordenar por Fecha de Modificación (Invertido)" },
	{ on = [ ",", "b" ], run = [ "sort btime --reverse=no", "linemode btime" ], desc = "Ordenar por Fecha de Creación" },
	{ on = [ ",", "B" ], run = [ "sort btime --reverse", "linemode btime" ],    desc = "Ordenar por Fecha de Creación (Invertido)" },
	{ on = [ ",", "e" ], run = "sort extension --reverse=no",                   desc = "Ordenar por Extensión" },
	{ on = [ ",", "E" ], run = "sort extension --reverse",                      desc = "Ordenar por Extensión (Invertido)" },
	{ on = [ ",", "a" ], run = "sort alphabetical --reverse=no",                desc = "Ordenar Alfabéticamente" },
	{ on = [ ",", "A" ], run = "sort alphabetical --reverse",                   desc = "Ordenar Alfabéticamente (Invertido)" },
	{ on = [ ",", "n" ], run = "sort natural --reverse=no",                     desc = "Ordenar Naturalmente" },
	{ on = [ ",", "N" ], run = "sort natural --reverse",                        desc = "Ordenar Naturalmente (Invertido)" },
	{ on = [ ",", "s" ], run = [ "sort size --reverse=no", "linemode size" ],   desc = "Ordenar por Tamaño" },
	{ on = [ ",", "S" ], run = [ "sort size --reverse", "linemode size" ],      desc = "Ordenar por Tamaño (Invertido)" },
	{ on = [ ",", "r" ], run = "sort random --reverse=no",                      desc = "Ordenar Aleatoriamente" },

	# Goto
	{ on = [ "g", "h" ], run = "cd ~",             desc = "Ir al Directorio Principal" },
	{ on = [ "g", "c" ], run = "cd ~/.config",     desc = "Ir a Configuraciones" },
	{ on = [ "g", "d" ], run = "cd ~/Descargas",   desc = "Ir Descargas" },
  { on = [ "g", "i" ], run = "cd --interactive", desc = "Saltar de Forma Interactiva" },

  { on = "F", run = "follow",           desc = "Seguir el Enlace Simbólico Seleccionado" },

	# Tabs
	{ on = [ "t", "t", ], run = "tab_create --current", desc = "Crear una Pestaña con la misma Ruta" },
	{ on = [ "t", "c", ], run = "close",                desc = "Cerrar Pestaña, ó Salir si es Única Pestaña" },

	{ on = "1", run = "tab_switch 0", desc = "Cambiar a la Primera Pestaña" },
	{ on = "2", run = "tab_switch 1", desc = "Cambiar a la Segunda Pestaña " },
	{ on = "3", run = "tab_switch 2", desc = "Cambiar a la Tercera Pestaña " },
	{ on = "4", run = "tab_switch 3", desc = "Cambiar a la Cuarta Pestaña " },
	{ on = "5", run = "tab_switch 4", desc = "Cambiar a la Quinta Pestaña " },
	{ on = "6", run = "tab_switch 5", desc = "Cambiar a la Sexta Pestaña " },
	{ on = "7", run = "tab_switch 6", desc = "Cambiar a la Séptima Pestaña " },
	{ on = "8", run = "tab_switch 7", desc = "Cambiar a la Octava Pestaña " },
	{ on = "9", run = "tab_switch 8", desc = "Cambiar a la Novena Pestaña " },

	{ on = "[", run = "tab_switch -1 --relative", desc = "Cambiar a la Pestaña Anterior" },
	{ on = "]", run = "tab_switch 1 --relative",  desc = "Cambiar a la Pestaña Siguente" },

{ on = "{", run = "tab_swap -1", desc = "Intercambiar la Pestaña Actual con la Anterior" },
{ on = "}", run = "tab_swap 1",  desc = "Intercambiar la Pestaña Actual con la Siguiente" },

	# Tasks
	{ on = "w", run = "tasks:show", desc = "Show Tareas en Curso" },

	# Help
	{ on = "<F1>", run = "help", desc = "Abrir Ayuda" },
]

prepend_keymap = [
{ on = ["T","a"], run = "plugin recycle-bin -- open",                     desc = "Abrir Papelera" },
{ on = ["T","v"], run = "plugin recyc --cursor=startle-bin -- empty",     desc = "Vaciar Papelera" },
{ on = ["T","V"], run = "plugin recycle-bin -- --cursor=start emptyDays", desc = "Vaciar Papelera por Días" },
{ on = ["T","e"], run = "plugin recycle-bin - --cursor=start- delete",    desc = "Eliminar de la Papelera" },
{ on = ["T","r"], run = "plugin recycle-bin -- re --cursor=startstore",   desc = "Restaurar desde la Papelera" },
]

[tasks]

keymap = [

	{ on = "<Esc>", run = "close", desc = "Cerrar Gestor de Tareas" },
	{ on = "<C-c>", run = "close", desc = "Cerrar Gestor de Tareas" },
	{ on = "w",     run = "close", desc = "Cerrar Gestor de Tareas" },

	{ on = "k", run = "arrow prev", desc = "Anterior Tarea" },
	{ on = "j", run = "arrow next", desc = "Siguente Tarea" },

	{ on = "<Up>",   run = "arrow prev", desc = "Anterior Tarea" },
	{ on = "<Down>", run = "arrow next", desc = "Siguente Tarea" },

	{ on = "<Enter>", run = "inspect", desc = "Revisar Tarea" },
	{ on = "x",       run = "cancel",  desc = "Cancelar Tarea" },

	# Help
	{ on = "<F1>", run = "help", desc = "Abrir Ayuda" },
]

[spot]

keymap = [
	{ on = "<Esc>", run = "close", desc = "Cerrar Propiedades" },
	{ on = "<C-c>", run = "close", desc = "Cerrar Propiedades" },
	{ on = "<Tab>", run = "close", desc = "Cerrar Propiedades" },

	{ on = "k", run = "arrow prev", desc = "Anterior Fila" },
	{ on = "j", run = "arrow next", desc = "Siguente Fila" },
	{ on = "h", run = "swipe prev", desc = "Cambiar al Anterior Archivo" },
	{ on = "l", run = "swipe next", desc = "Cambiar al Siguente Archivo" },

	{ on = "<Up>",    run = "arrow prev", desc = "Anterior Fila" },
	{ on = "<Down>",  run = "arrow next", desc = "Siguente Fila" },
	{ on = "<Left>",  run = "swipe prev", desc = "Cambiar al Anterior Archivo" },
	{ on = "<Right>", run = "swipe next", desc = "Cambiar al Siguente Archivo" },

	# Copy
	{ on =  "c" , run = "copy cell", desc = "Copiar Fila" },

	# Help
	{ on = "<F1>", run = "help", desc = "Abrir Ayuda" },
]

[pick]

keymap = [
	{ on = "<Esc>",   run = "close",          desc = "Cancelar Selección" },
	{ on = "<C-c>",   run = "close",          desc = "Cancelar Selección" },
	{ on = "<Enter>", run = "close --submit", desc = "Aceptar Selección" },

	{ on = "k", run = "arrow prev", desc = "Anterior Opción" },
	{ on = "j", run = "arrow next", desc = "Siguente Opción" },

	{ on = "<Up>",   run = "arrow prev", desc = "Anterior Opción" },
	{ on = "<Down>", run = "arrow next", desc = "Siguente Opción" },

	# Help
	{ on = "<F1>", run = "help", desc = "Abrir Ayuda" },
]

[input]

keymap = [
	{ on = "<Esc>",   run = "escape",         desc = "Regresar al Modo Normal o Cancelar" },
	{ on = "<C-c>",   run = "close",          desc = "Cancelar" },
	{ on = "<Enter>", run = "close --submit", desc = "Confirmar" },

	# Mode
	{ on = "i", run = "insert",                          desc = "Entrar al Modo Insertar al Anterior Carácter " },
	{ on = "I", run = [ "move bol", "insert" ],          desc = "Entrar al Modo Insertar al Inicio de la Fila" },
	{ on = "a", run = "insert --append",                 desc = "Entrar al Modo Insertar al Siguiente carácter" },
	{ on = "A", run = [ "move eol", "insert --append" ], desc = "Entrar al Modo Insertar al Final de la Fila" },
	{ on = "v", run = "visual",                          desc = "Entrar al Modo Visual" },
	{ on = "r", run = "replace",                         desc = "Reemplazar Carácter" },

	# Selection
	{ on = "V",     run = [ "move bol", "visual", "move eol" ], desc = "Seleccionar Fila Completa" },
	{ on = "<C-i>", run = [ "visual", "move first-char" ],      desc = "Seleccionar hasta Inicio de la Fila" },
	{ on = "<C-a>", run = [ "visual", "move eol" ],             desc = "Seleccionar hasta el Final de la Fila" },

	# Character-wise movement
	{ on = "h",       run = "move -1", desc = "Mover Atrás un Carácter" },
	{ on = "l",       run = "move 1",  desc = "Mover Adelante un Carácter" },
	{ on = "<Left>",  run = "move -1", desc = "Mover Atrás un Carácter" },
	{ on = "<Right>", run = "move 1",  desc = "Mover Adelante un Carácter" },

	# Word-wise movement
  { on = "b", run = "backward",                    desc = "Mover al Inicio de la Palabra Actual o Anterior" },
  { on = "B", run = "backward --far",              desc = "Mover al Inicio de la PALABRA Actual o Anterior" },
  { on = "w", run = "forward",                     desc = "Mover al Inicio de la Siguiente Palabra" },
  { on = "W", run = "forward --far",               desc = "Mover al Inicio de la Siguiente PALABRA" },
  { on = "e", run = "forward --end-of-word",       desc = "Mover al Final de la Palabra Actual o Siguiente" },
  { on = "E", run = "forward --far --end-of-word", desc = "Mover al Final de la PALABRA Actual o Siguiente" },

	# Line-wise movement
	{ on = "0", run = "move bol",        desc = "Mover al Inicio de la Fila" },
	{ on = "$", run = "move eol",        desc = "Mover al Final de la Fila" },
	{ on = "_", run = "move first-char", desc = "Mover al Primer Carácter (NO Espacio en Blanco)" },

	# Delete
	{ on = "<Backspace>", run = "backspace",         desc = "Borrar hacia Atrás del Cursor" },
	{ on = "<Delete>",    run = "backspace --under", desc = "Borrar hacia Adelante del Cursor" },

	# Kill
  { on = "<C-h>", run = "kill bol",      desc = "Eliminar hacia Atrás hasta el Inicio de la Fila" },
  { on = "<C-l>", run = "kill eol",      desc = "Eliminar hacia Adelante hasta el Final de la Fila" },
  { on = "<C-b>", run = "kill backward", desc = "Eliminar hacia Atrás hasta el Inicio de la Palabra Actual" },
  { on = "<A-e>", run = "kill forward",  desc = "Eliminar hacia Adelante hasta el Final de la Palabra Actual" },

	# Cut/Yank/Paste
  { on = "d", run = "delete --cut",                                      desc = "Cortar los Caracteres Seleccionados" },
  { on = "D", run = [ "delete --cut", "move eol" ],                      desc = "Cortar hasta el Final de la Fila" },
  { on = "c", run = "delete --cut --insert",                             desc = "Cortar los Caracteres Seleccionados y Entrar en Modo de Insertar" },
  { on = "C", run = [ "delete --cut --insert", "move eol" ],             desc = "Cortar hasta el Final de la Fila y Entrar en Modo de Insertar" },
  { on = "s", run = [ "delete --cut --insert", "move 1" ],               desc = "Cortar el Carácter Actual y Entrar en Modo de Insertar" },
  { on = "S", run = [ "move bol", "delete --cut --insert", "move eol" ], desc = "Cortar desde el Inicio hasta el Final de la Fila y Entrar en Modo de Insertar" },
  { on = "x", run = [ "delete --cut", "move 1 --in-operating" ],         desc = "Cortar el Carácter Actual" },
  { on = "y", run = "yank",                                              desc = "Copiar los Caracteres Seleccionados" },
  { on = "p", run = "paste",                                             desc = "Pegar los Caracteres Copiados después del Cursor" },
  { on = "P", run = "paste --before",                                    desc = "Pegar los Caracteres Copiados antes del Cursor" },

	# Undo/Redo
  { on = "u", run = "undo", desc = "Deshacer la Última Operación" },
  { on = "U", run = "redo", desc = "Rehacer la Última Operación" },

	# Help
	{ on = "<F1>", run = "help", desc = "Abrir Ayuda" },
]

[confirm]

keymap = [
	{ on = "<Esc>",   run = "close",          desc = "Cancelar Confirmación" },
	{ on = "<Enter>", run = "close --submit", desc = "Enviar Confirmación" },

	{ on = "n", run = "close",          desc = "Cancelar Confirmación" },
	{ on = "y", run = "close --submit", desc = "Enviar Confirmación" },

	{ on = "k", run = "arrow prev", desc = "Anterior Fila" },
	{ on = "j", run = "arrow next", desc = "Siguente Fila" },

	{ on = "<Up>",   run = "arrow prev", desc = "Anterior Fila" },
	{ on = "<Down>", run = "arrow next", desc = "Anterior Fila" },

	# Help
	{ on = "<F1>", run = "help", desc = "Abrir Ayuda" },
]

[cmp]

keymap = [
	{ on = "<C-c>",   run = "close",                                      desc = "Cancelar Finalización" },
	{ on = "<Tab>",   run = "close --submit",                             desc = "Enviar Finalización" },
	{ on = "<Enter>", run = [ "close --submit", "input:close --submit" ], desc = "Completar y Confirmar" },

	{ on = "<k>", run = "arrow prev", desc = "Anterior Elemento" },
	{ on = "<j>", run = "arrow next", desc = "Siguente Elemento" },

	{ on = "<Up>",   run = "arrow prev", desc = "Anterior Elemento" },
	{ on = "<Down>", run = "arrow next", desc = "Siguente Elemento" },

	# Help
	{ on = "<F1>", run = "help", desc = "Abrir Ayuda" },
]

[help]

keymap = [
	{ on = "<Esc>", run = "escape", desc = "Limpiar Filtro u Ocultar Ayuda" },
	{ on = "<C-c>", run = "close",  desc = "Ocultar Ayuda" },

	# Navigation
	{ on = "k", run = "arrow prev", desc = "Anterior Fila" },
	{ on = "j", run = "arrow next", desc = "Siguente Fila" },

	{ on = "<Up>",   run = "arrow prev", desc = "Anterior Fila" },
	{ on = "<Down>", run = "arrow next", desc = "Siguente Fila" },

	# Filtering
	{ on = "f", run = "filter", desc = "Filtrar Elementos de Ayuda" },
]
