################
### HARDWARE ###
################

# Laptop multimedia keys for volume and LCD brightness
binddel = ,XF86Audioraisevolume,  Subir Volumen,       exec, $subir_volumen
binddel = ,XF86Audiolowervolume,  Bajar Volumen,       exec, $bajar_volumen
binddl = ,XF86Audiomute,         Silenciar Volumen,   exec, $silenciar_volumen
binddl = ,XF86Audiomicmute,      Silenciar Micrófono, exec, $silenciar_microfono

binddel = ,XF86Monbrightnessup,   Subir Brillo, exec, $subir_brillo
binddel = ,XF86Monbrightnessdown, Bajar Brillo, exec, $bajar_brillo

# Requires playerctl
binddl = , XF86Audionext, Siguiente Pista,      exec, $siguiente_pista
binddl = , XF86Audioplay, Pausar o Reproducir,  exec, $pausar_reproducir
binddl = , XF86Audiostop, Detener Reproducción, exec, $detener_reproduccion
binddl = , XF86Audioprev, Anterior Pista,       exec, $anterior_pista
