################
### HARDWARE ###
################

# Laptop multimedia keys for volume and LCD brightness
binddel = ,XF86AudioRaiseVolume,  Subir Volumen,       exec, $subir_volumen
binddel = ,XF86AudioLowerVolume,  Bajar Volumen,       exec, $bajar_volumen
binddel = ,XF86AudioMute,         Silenciar Volumen,   exec, $silenciar_volumen
binddel = ,XF86AudioMicMute,      Silenciar Micrófono, exec, $silenciar_microfono
binddel = ,XF86MonBrightnessUp,   Subir Volumen,       exec, $subir_brillo
binddel = ,XF86MonBrightnessDown, Bajar Volumen,       exec, $bajar_brillo

# Requires playerctl
binddl = , XF86AudioNext, Siguiente Pista,      exec, $siguiente_pista
binddl = , XF86AudioPlay, Pausar o Reproducir,  exec, $pausar_reproducir
binddl = , XF86AudioStop, Detener Reproducción, exec, $detener_reproduccion
binddl = , XF86AudioPrev, Anterior Pista,       exec, $anterior_pista
