#################
### SCROLLING ###
#################
bindd = $mainMod,       R, Aumentar Ancho Predeterminado de Ventana (Scrolling), layoutmsg, colresize +conf
bindd = $mainMod SHIFT, R, Reducir Ancho Predeterminado de Ventana (Scrolling),  layoutmsg, colresize -conf

bindd = $mainMod, Plus,  Incrementar Dimensión de Ventana (Scrolling), layoutmsg, colresize +0.05
bindd = $mainMod, Minus, Disminuir Dimensión de Ventana (Scrolling),   layoutmsg, colresize -0.05

bindd = $mainMod, D, Cambiar Ventana a la Derecha (Scrolling),   layoutmsg, swapcol r
bindd = $mainMod, I, Cambiar Ventana a la Izquierda (Scrolling), layoutmsg, swapcol l

bindd = $mainMod,       W, Maximizar Ventana (Scrolling),                              layoutmsg, fit active
bindd = $mainMod SHIFT, W, Ajustar Ventanas visibles al Ancho de Pantalla (Scrolling), layoutmsg, fit visible
bindd = $mainMod CTRL,  W, Ajustar Ventanas al Ancho de la pantalla (Scrolling),       layoutmsg, fit all
