##############
### MASTER ###
##############

bindd = $mainMod,       P, Enfocar Siguiente Ventana (Master), layoutmsg, cyclenext loop
bindd = $mainMod SHIFT, P, Enfocar Anterior Ventana (Master),  layoutmsg, cycleprev loop

bindd = $mainMod,       O, Enfocar Ventana Maestra (Master),                    layoutmsg, focusmaster auto
bindd = $mainMod SHIFT, O, Intercambia Ventana con la Ventana Maestra (Master), layoutmsg, swapwithmaster auto

bindd = $mainMod,       I, Intercambia Ventana con la Siguiente (Master), layoutmsg, swapnext loop
bindd = $mainMod SHIFT, I, Intercambia Ventana con la Anterior (Master),  layoutmsg, swapprev loop

bindd = $mainMod,      Tab, Rotar Ventanas (Master),         layoutmsg, rollprev
bindd = $mainMod SHIFT,Tab, Rotar Ventanas Inverso (Master), layoutmsg, rollnext

bindd = $mainMod, Plus,  Incrementar Dimensión de Ventana Maestra (Master), layoutmsg, mfact +0.05
bindd = $mainMod, Minus, Disminuir Dimensión de Ventana Maestra (Master),   layoutmsg, mfact -0.05

bindd = $mainMod CTRL, Return, Cambiar Orientación de Ventanas Esclavas (Master), layoutmsg, orientationnext
