##############
### MASTER ###
##############

bindd = $mainMod, L, Enfocar Siguiente Ventana (Master), layoutmsg, cyclenext loop
bindd = $mainMod, H, Enfocar Anterior Ventana (Master),  layoutmsg, cycleprev loop

bindd = $mainMod SHIFT, L, Intercambia Ventana con la Siguiente (Master), layoutmsg, swapnext loop
bindd = $mainMod SHIFT, H, Intercambia Ventana con la Anterior (Master),  layoutmsg, swapprev loop

bindd = $mainMod CTRL, L, Rotar Ventanas (Master),         layoutmsg, rollprev
bindd = $mainMod CTRL, H, Rotar Ventanas Inverso (Master), layoutmsg, rollnext

bindd = $mainMod,       M, Enfocar Ventana Maestra (Master),                    layoutmsg, focusmaster auto
bindd = $mainMod SHIFT, M, Intercambia Ventana con la Ventana Maestra (Master), layoutmsg, swapwithmaster auto

bindd = $mainMod, Plus,  Incrementar Dimensión de Ventana Maestra (Master), layoutmsg, mfact +0.05
bindd = $mainMod, Minus, Disminuir Dimensión de Ventana Maestra (Master),   layoutmsg, mfact -0.05

bindd = $mainMod,       Tab, Cambiar Orientación de Ventanas Esclavas (Master),         layoutmsg, orientationnext
bindd = $mainMod SHIFT, Tab, Cambiar Orientación de Ventanas Esclavas Inverso (Master), layoutmsg, orientationprev
