###############
### DWINDLE ###
###############

bindd = $mainMod, S, Intercambia Posición de Ventanas (Dwindle), layoutmsg, swapsplit
bindd = $mainMod, A, Alterna disposición de Ventanas (Dwindle),  layoutmsg, togglesplit

bindd = $mainMod, H, Abrir Siguiente Ventana a la Izquierda (Dwindle), layoutmsg, preselect l
bindd = $mainMod, L, Abrir Siguiente Ventana a la Derecha (Dwindle),   layoutmsg, preselect r
bindd = $mainMod, K, Abrir Siguiente Ventana hacia Arriba (Dwindle),   layoutmsg, preselect u
bindd = $mainMod, J, Abrir Siguiente Ventana hacia Abajo (Dwindle),    layoutmsg, preselect d
