#################
### SCROLLING ###
#################
bindd = $mainMod SHIFT, R, Aumentar Ancho Predeterminado de Ventana (Scrolling), layoutmsg, colresize +conf
bindd = $mainMod,       R, Reducir Ancho Predeterminado de Ventana (Scrolling),  layoutmsg, colresize -conf

bindd = $mainMod, Plus,  Incrementar Dimensión de Ventana (Scrolling), layoutmsg, colresize +0.05
bindd = $mainMod, Minus, Disminuir Dimensión de Ventana (Scrolling),   layoutmsg, colresize -0.05

bindd = $mainMod, L, Cambiar Ventana a Columna de la Derecha (Scrolling),   layoutmsg, swapcol r
bindd = $mainMod, H, Cambiar Ventana a Columna de la Izquierda (Scrolling), layoutmsg, swapcol l

bindd = $mainMod, I, Pasar Ventana a Columna Independiente Derecha (Scrolling), layoutmsg, promote

bindd = $mainMod, A, Ajustar Ventanas visibles al Ancho de Pantalla (Scrolling), layoutmsg, fit visible
bindd = $mainMod, S, Ajustar Ventanas al Ancho de la pantalla (Scrolling),       layoutmsg, fit all
