###############
### DWINDLE ###
###############

bindd = $mainMod, I, Intercambia Posición de Ventanas (Dwindle), layoutmsg, swapsplit
bindd = $mainMod, O, Alterna disposición de Ventanas (Dwindle),  layoutmsg, togglesplit
bindd = $mainMod, P, Pseudoflotante (Dwindle),                   pseudo
