##############
### MASTER ###
##############

bindd = $mainMod, S, Enfocar Siguiente Ventana (Maestro), layoutmsg, cyclenext loop
bindd = $mainMod, A, Enfocar Anterior Ventana (Maestro),  layoutmsg, cycleprev loop

bindd = $mainMod SHIFT, S, Intercambia Ventana con la Siguiente (Maestro), layoutmsg, swapnext loop
bindd = $mainMod SHIFT, A, Intercambia Ventana con la Anterior (Maestro),  layoutmsg, swapprev loop

bindd = $mainMod CTRL, S, Rotar Ventanas (Maestro),         layoutmsg, rollprev
bindd = $mainMod CTRL, A, Rotar Ventanas Inverso (Maestro), layoutmsg, rollnext

bindd = $mainMod, O, Enfocar Ventana Maestra (Maestro),                    layoutmsg, focusmaster previous
bindd = $mainMod, I, Intercambia Ventana con la Ventana Maestra (Maestro), layoutmsg, swapwithmaster auto

bindd = $mainMod, Plus,  Incrementar Dimensión de Ventana Maestra (Maestro), layoutmsg, mfact +0.05
bindd = $mainMod, Minus, Disminuir Dimensión de Ventana Maestra (Maestro),   layoutmsg, mfact -0.05

bindd = $mainMod,       R, Remover una Ventana Maestra (Maestro), layoutmsg, removemaster
bindd = $mainMod SHIFT, R, Añadir una Ventana Maestra (Maestro),  layoutmsg, addmaster

# bindd = $mainMod,       Tab, Cambiar Orientación de Ventanas Esclavas (Maestro),         layoutmsg, orientationnext
# bindd = $mainMod SHIFT, Tab, Cambiar Orientación de Ventanas Esclavas Inverso (Maestro), layoutmsg, orientationprev
