###############
### DWINDLE ###
###############

bindd = $mainMod, S, Intercambia Posición de Ventanas (Mosaico), layoutmsg, swapsplit
bindd = $mainMod, A, Alterna disposición de Ventanas (Mosaico),  layoutmsg, togglesplit

bindd = $mainMod, H, Abrir Siguiente Ventana a la Izquierda (Mosaico), layoutmsg, preselect l
bindd = $mainMod, L, Abrir Siguiente Ventana a la Derecha (Mosaico),   layoutmsg, preselect r
bindd = $mainMod, K, Abrir Siguiente Ventana hacia Arriba (Mosaico),   layoutmsg, preselect u
bindd = $mainMod, J, Abrir Siguiente Ventana hacia Abajo (Mosaico),    layoutmsg, preselect d
