#################
### SCROLLING ###
#################

bindd = $mainMod,       R, Reducir Ancho Predeterminado de Ventana (Desplazamiento),  layoutmsg, colresize -conf
bindd = $mainMod SHIFT, R, Aumentar Ancho Predeterminado de Ventana (Desplazamiento), layoutmsg, colresize +conf

bindd = $mainMod, Plus,  Incrementar Dimensión de Ventana (Desplazamiento), layoutmsg, colresize +0.05
bindd = $mainMod, Minus, Disminuir Dimensión de Ventana (Desplazamiento),   layoutmsg, colresize -0.05

bindd = $mainMod, L, Cambiar Ventana a Columna de la Derecha (Desplazamiento),   layoutmsg, swapcol r
bindd = $mainMod, H, Cambiar Ventana a Columna de la Izquierda (Desplazamiento), layoutmsg, swapcol l

bindd = $mainMod, I, Pasar Ventana a Columna Independiente Derecha (Desplazamiento), layoutmsg, promote

bindd = $mainMod, A, Ajustar Ventanas visibles al Ancho de Pantalla (Desplazamiento), layoutmsg, fit visible
bindd = $mainMod, S, Ajustar Ventanas al Ancho de la pantalla (Desplazamiento),       layoutmsg, fit all
