###############
### MONOCLE ###
###############

bindd = $mainMod,      Tab, Traer Siguente Ventana al Frente (Monocle), layoutmsg, cyclenext
bindd = $mainMod SHIFT,Tab, Traer Anterior Ventana al Frente (Monocle), layoutmsg, cycleprev
