#####################
### MISCELLANEOUS ###
#####################

bindd = $mainMod,       Return, Terminal,                   exec, $terminal
bindd = $mainMod SHIFT, Return, Terminal Flotante,          exec, $terminal_flotante
bindd = $mainMod,       B,      Google Chrome,              exec, $chrome
bindd = $mainMod SHIFT, B,      Firefox,                    exec, $firefox
bindd = $mainMod,       F1,     Atajos de Hyprland,         exec, $atajos
bindd = $mainMod SHIFT, Space,  Cambiar de LAYOUT,          exec, $layout
bindd = $mainMod CTRL,  Space,  Cambiar de LAYOUT Inverso,  exec, $layout -r
bindd = $mainMod CTRL,  Escape, Salir de Hyprland,          exec, $salir

bindd = $mainMod,       Space,  Menú de Aplicaciones,             exec, $menu
bindd = $mainMod SHIFT, L,      Bloquear Pantalla,                exec, $bloquear_pantalla
bindd = $mainMod SHIFT, Escape, Menú de Sesión,                   exec, $power_menu
bindd = $mainMod,       N,      Centro de Notificaciones,         exec, $centro_notificaciones
bindd = $mainMod SHIFT, N,      Borrar Notificaciones Pendientes, exec, $borrar_notificaciones
bindd = $mainMod SHIFT, C,      Centro de Control,                exec, $centro_control
bindd = $mainMod CTRL,  C,      Calendario,                       exec, $calendario
bindd = $mainMod,       W,      Selector de Fondos de Pantalla,   exec, $wallpaper_selector
bindd = $mainMod SHIFT, W,      Cambiar de Fondo de Pantalla,     exec, $wallpaper_random
bindd = $mainMod,       Z,      Alternar Inhibidor,               exec, $idle_inhibidor
bindd = $mainMod,       X,      Alterar Barra de Estado,          exec, $toggle_bar

bindd = ,         PRINT, Captura de Ventana,  exec, $captura_ventana
bindd = $mainMod, PRINT, Captura de Pantalla, exec, $captura_pantalla
bindd = SHIFT,    PRINT, Captura de Área,     exec, $captura_area
