#####################
### MISCELLANEOUS ###
#####################

bindd = $mainMod,       Return, Terminal,               exec, $terminal
bindd = $mainMod SHIFT, Return, Terminal Flotante,      exec, $terminal_float
bindd = $mainMod,       B,      Google Chrome,          exec, $chrome
bindd = $mainMod SHIFT, B,      Firefox,                exec, $firefox
bindd = $mainMod,       E,      Explorador de Archivos, exec, $file_manager
bindd = $mainMod,       F1,     Atajos de Hyprland,     exec, $atajos
bindd = $mainMod CTRL,  Escape, Salir de Hyprland,      exec, $salir

bindd = $mainMod,       D,   Cambiar de LAYOUT,                                 exec, $layout
bindd = $mainMod SHIFT, D,   Cambiar de LAYOUT Inverso,                         exec, $layout -r
bindd = $mainMod,       Tab, Cambiar de ORIENTACIÓN (Maestro/Desplazamiento),         exec, $layout -o
bindd = $mainMod SHIFT, Tab, Cambiar de ORIENTACIÓN Inverso (Maestro/Desplazamiento), exec, $layout -r -o

bindd = $mainMod,       Space,  Menú de Aplicaciones,             exec, $menu
bindd = $mainMod SHIFT, L,      Bloquear Pantalla,                exec, $bloquear_pantalla
bindd = $mainMod SHIFT, Escape, Menú de Sesión,                   exec, $power_menu
bindd = $mainMod,       N,      Centro de Notificaciones,         exec, $centro_notificaciones
bindd = $mainMod SHIFT, N,      Borrar Notificaciones Pendientes, exec, $borrar_notificaciones
bindd = $mainMod SHIFT, C,      Centro de Control,                exec, $centro_control
bindd = $mainMod CTRL,  C,      Calendario,                       exec, $calendario
bindd = $mainMod,       W,      Selector de Fondos de Pantalla,   exec, $wallpaper_selector
bindd = $mainMod SHIFT, W,      Cambiar de Fondo de Pantalla,     exec, $wallpaper_random
bindd = $mainMod,       Z,      Alternar Inhibidor,               exec, $idle_inhibidor
bindd = $mainMod,       X,      Alterar Barra de Estado,          exec, $toggle_bar

binde = $mainMod CTRL, Plus,  exec, $zoom_p
binde = $mainMod CTRL, Minus, exec, $zoom_m

bindd = ,         PRINT, Captura de Ventana,  exec, $captura_ventana
bindd = $mainMod, PRINT, Captura de Pantalla, exec, $captura_pantalla
bindd = SHIFT,    PRINT, Captura de Área,     exec, $captura_area
