###############
### WINDOWS ###
###############

# Move focus with mainMod + arrow keys
bindd = $mainMod, Left,  Enfocar Ventana de la Izquierda, movefocus,  l
bindd = $mainMod, Right, Enfocar Ventana de la Derecha,   movefocus,  r
bindd = $mainMod, Up,    Enfocar Ventana de Arriba,       movefocus,  u
bindd = $mainMod, Down,  Enfocar Ventana de Abajo,        movefocus,  d

bindd = $mainMod SHIFT, Left,  Mover Ventana hacia la Izquierda, movewindow, l
bindd = $mainMod SHIFT, Right, Mover Ventana hacia la Derecha,   movewindow, r
bindd = $mainMod SHIFT, Up,    Mover Ventana hacia Arriba,       movewindow, u
bindd = $mainMod SHIFT, Down,  Mover Ventana hacia Abajo,        movewindow, d

bindde = $mainMod CTRL, Left,  Mover Ventana Flotante hacia la Izquierda, moveactive, -20 0
bindde = $mainMod CTRL, Right, Mover Ventana Flotante hacia la Derecha,   moveactive, 20 0
bindde = $mainMod CTRL, Up,    Mover Ventana Flotante hacia Arriba,       moveactive, 0 -20
bindde = $mainMod CTRL, Down,  Mover Ventana Flotante hacia Abajo,        moveactive, 0 20

bindde = $mainMod ALT, Left,  Reducir Ancho de Ventana Flotante,                    resizeactive, -10 0
bindde = $mainMod ALT, Right, Aumentar Altura de Ventana Flotante hacia la Derecha, resizeactive, 10 0
bindde = $mainMod ALT, Up,    Aumentar Altura de Ventana Flotante hacia Arriba,     resizeactive, 0 10
bindde = $mainMod ALT, Down,  Reducir Ancho de Ventana Flotante hacia Abajo,        resizeactive, 0 -10

# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bindd = $mainMod,       Q, Cerrar Ventana,                               killactive,
bindd = $mainMod SHIFT, Q, Matar Todas las Instancias de una Aplicación, killwindow,
bindd = $mainMod,       F, Pantalla Completa,                            fullscreen, 0
bindd = $mainMod SHIFT, F, Maximizar Ventana,                            fullscreen, 1
bindd = $mainMod CTRL,  F, Pantalla Completa(Fake),                      fullscreenstate, 0 3

bindd = $mainMod,       V, Alternar a Flotante,        togglefloating,
bindd = $mainMod SHIFT, V, Enfocar Ventanas Flotantes, cyclenext, floating
bindd = $mainMod SHIFT, P, Fijar Ventana Flotante,     pin,
bindd = $mainMod,       C, Centrar Ventana Flotante,   centerwindow,

# Move/resize windows with mainMod + LMB/RMB and dragging
binddm = $mainMod,       mouse:272, Mover Ventana (Mouse),         movewindow
binddm = $mainMod SHIFT, mouse:272, Redimensionar Ventana (Mouse), resizewindow
