###############
### WINDOWS ###
###############

# Move focus with mainMod + arrow keys
bindd = $mainMod, Left,  Enfocar Ventana de la Izquierda, movefocus,  l
bindd = $mainMod, Right, Enfocar Ventana de la Derecha,   movefocus,  r
bindd = $mainMod, Up,    Enfocar Ventana de Arriba,       movefocus,  u
bindd = $mainMod, Down,  Enfocar Ventana de Abajo,        movefocus,  d

bindd = $mainMod SHIFT, Left,  Mover Ventana hacia la Izquierda, movewindow, l
bindd = $mainMod SHIFT, Right, Mover Ventana hacia la Derecha,   movewindow, r
bindd = $mainMod SHIFT, Up,    Mover Ventana hacia Arriba,       movewindow, u
bindd = $mainMod SHIFT, Down,  Mover Ventana hacia Abajo,        movewindow, d

bindde = $mainMod CTRL, left,  Mover Ventana Flotante hacia la Izquierda, moveactive, -20 0
bindde = $mainMod CTRL, right, Mover Ventana Flotante hacia la Derecha,   moveactive, 20 0
bindde = $mainMod CTRL, up,    Mover Ventana Flotante hacia Arriba,       moveactive, 0 -20
bindde = $mainMod CTRL, down,  Mover Ventana Flotante hacia Abajo,        moveactive, 0 20

bindde = $mainMod ALT, left,  Mover Ventana Flotante hacia la Izquierda, resizeactive, -10 0
bindde = $mainMod ALT, right, Mover Ventana Flotante hacia la Derecha,   resizeactive, 10 0
bindde = $mainMod ALT, up,    Mover Ventana Flotante hacia Arriba,       resizeactive, 0 10
bindde = $mainMod ALT, down,  Mover Ventana Flotante hacia Abajo,        resizeactive, 0 -10

# Move/resize windows with mainMod + LMB/RMB and dragging
binddm = $mainMod,       mouse:272, Mover Ventana (Mouse),         movewindow
binddm = $mainMod SHIFT, mouse:272, Redimensionar Ventana (Mouse), resizewindow
