##################
### ANIMATIONS ###
##################

# Enabling Animations
animations       = 1
layer_animations = 1

# Animation Types
animation_type_open        = zoom
animation_type_close       = zoom
layer_animation_type_open  = fade
layer_animation_type_close = fade

# Fade Settings
animation_fade_in     = 1
animation_fade_out    = 1
fadein_begin_opacity  = 0.4
fadeout_begin_opacity = 0.8

#Zoom Settings
zoom_initial_ratio = 0.4
zoom_end_ratio     = 0.8

# Durations
animation_duration_move  = 500
animation_duration_open  = 400
animation_duration_tag   = 300
animation_duration_close = 300
animation_duration_focus = 0

# Custom Bezier Curves
animation_curve_open       = 0,    0.55, 0.45, 1
animation_curve_move       = 0,    0.55, 0.45, 1
animation_curve_tag        = 0,    0.55, 0.45, 1
animation_curve_close      = 0.85, 0,    0.15, 1
animation_curve_focus      = 0.85, 0,    0.15, 1
animation_curve_opafadein  = 0,    0.55, 0.45, 1
animation_curve_opafadeout = 0.85, 0,    0.15, 1

# Tag Animation Direction
tag_animation_direction=1
