# Appearance
borderpx=3
gappih=4
gappiv=4
gappoh=8
gappov=8

maximizescreencolor=0x89aa61ff
scratchpadcolor=0x516c93ff
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff

rootcolor=0x201b14ff
bordercolor=0x444444ff
focuscolor=0xc9b8ffff
urgentcolor=0xad401fff
