# movewin
bind=SUPER+CTRL,Up,smartmovewin,up,
bind=SUPER+CTRL,Down,smartmovewin,down,
bind=SUPER+CTRL,Left,smartmovewin,left,
bind=SUPER+CTRL,Right,smartmovewin,right,

# resizewin
bind=SUPER+ALT,Up,resizewin,+0,-20
bind=SUPER+ALT,Down,resizewin,+0,+20
bind=SUPER+ALT,Left,resizewin,-20,+0
bind=SUPER+ALT,Right,resizewin,+20,+0

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
