# reload config
bind=SUPER+CTRL,R,reload_config

# exit
bind=SUPER+CTRL,Escape,quit

bind=SUPER,Escape,toggleoverview
bind=SUPER+SHIFT,G,toggleoverlay

gesturebind=none,up,4,toggleoverview,1
gesturebind=none,down,4,toggleoverview,1
