##################################
### FLOATING WINDOW MANAGEMENT ###
##################################

# Smartmovewin
bind = SUPER+CTRL, Up,    smartmovewin, up
bind = SUPER+CTRL, Down,  smartmovewin, down
bind = SUPER+CTRL, Left,  smartmovewin, left
bind = SUPER+CTRL, Right, smartmovewin, right

# Resizewin
bind = SUPER+ALT, Up,    resizewin, +0,  -10
bind = SUPER+ALT, Down,  resizewin, +0,  +10
bind = SUPER+ALT, Left,  resizewin, -10, +0
bind = SUPER+ALT, Right, resizewin, +10, +0

# MOUSE
mousebind = SUPER,     btn_left, moveresize, curmove
mousebind = SUPER+ALT, btn_left, moveresize, curresize
