########################
### FOCUS & MOVEMENT ###
########################

# switch window focus
bind = SUPER, Left,  focusdir, left
bind = SUPER, Right, focusdir, right
bind = SUPER, Up,    focusdir, up
bind = SUPER, Down,  focusdir, down

bind = SUPER, A, focusstack, prev
bind = SUPER, S, focusstack, next

# swap window
bind = SUPER+SHIFT, Up,    exchange_client, up
bind = SUPER+SHIFT, Down,  exchange_client, down
bind = SUPER+SHIFT, Left,  exchange_client, left
bind = SUPER+SHIFT, Right, exchange_client, right

bind = SUPER+SHIFT, A, exchange_stack_client, prev
bind = SUPER+SHIFT, S, exchange_stack_client, next

bind = SUPER,Tab, focuslast

bind = SUPER, I, zoom
