################
### HARDWARE ###
################

# brightness and volume
bindl = NONE, XF86AudioRaiseVolume, spawn, qs -c noctalia-shell ipc call volume increase
bindl = NONE, XF86AudioLowerVolume, spawn, qs -c noctalia-shell ipc call volume decrease
bindl = NONE, XF86AudioMute,        spawn, qs -c noctalia-shell ipc call volume muteOutput
bindl = NONE, XF86AudioMicMute,     spawn, qs -c noctalia-shell ipc call volume muteInput

bindl = NONE, XF86MonBrightnessUp,   spawn, qs -c noctalia-shell ipc call brightness increase
bindl = NONE, XF86MonBrightnessDown, spawn, qs -c noctalia-shell ipc call brightness decrease

# Requires playerctl
bindl = NONE, XF86Audionext, spawn, qs -c noctalia-shell ipc call media playPause
bindl = NONE, XF86Audioplay, spawn, qs -c noctalia-shell ipc call media stop
bindl = NONE, XF86Audiostop, spawn, qs -c noctalia-shell ipc call media previous
bindl = NONE, XF86Audioprev, spawn, qs -c noctalia-shell ipc call media next
