###############
### LAYOUTS ###
###############

# switch layout
bind = SUPER,      D, switch_layout
bind = SUPER+CTRL, T, setlayout,    tile
bind = SUPER+CTRL, S, setlayout,    scroller

# Incnmaster
bind = SUPER,       T, incnmaster, +1
bind = SUPER+SHIFT, T, incnmaster, -1

# Setmfact
bind = SUPER, Plus,    setmfact, +0.05
bind = SUPER, code:61, setmfact, -0.05

# Switch proportion preset preset
bind = SUPER, R, switch_proportion_preset

bind = CTRL+ALT, Left,  scroller_stack, left
bind = CTRL+ALT, Right, scroller_stack, right
bind = CTRL+ALT, Up,    scroller_stack, up
bind = CTRL+ALT, Down,  scroller_stack, down

# Incgaps
bind = SUPER+SHIFT, code:35, incgaps, +1
bind = SUPER+SHIFT, code:61, incgaps, -1
bind = SUPER+SHIFT, R,       togglegaps
