###############
### LAYOUTS ###
###############

# switch layout
bind = SUPER,       D, switch_layout

bind = SUPER,       H, setlayout, tile
bind = SUPER+SHIFT, H, setlayout, grid
bind = SUPER+CTRL,  H, setlayout, monocle

bind = SUPER,       L, setlayout, scroller
bind = SUPER+SHIFT, L, setlayout, deck
bind = SUPER+CTRL,  L, setlayout, tgmix

bind = SUPER,       J, setlayout, vertical_tile
bind = SUPER+SHIFT, J, setlayout, vertical_grid
bind = SUPER+CTRL,  J, setlayout, center_tile

bind = SUPER,       K, setlayout, vertical_scroller
bind = SUPER+SHIFT, K, setlayout, vertical_deck
bind = SUPER+CTRL,  K, setlayout, right_tile

# Incnmaster
bind = SUPER,       P, incnmaster, +1
bind = SUPER+SHIFT, P, incnmaster, -1

# Setmfact
bind = SUPER, code:35, setmfact, +0.05
bind = SUPER, code:61, setmfact, -0.05

# Switch proportion preset preset
bind = SUPER, R, switch_proportion_preset

# Scroller stack
bind = CTRL+ALT, Left,  scroller_stack, left
bind = CTRL+ALT, Right, scroller_stack, right
bind = CTRL+ALT, Up,    scroller_stack, up
bind = CTRL+ALT, Down,  scroller_stack, down

# Gaps
bind = SUPER+SHIFT, code:35, incgaps, +1
bind = SUPER+SHIFT, code:61, incgaps, -1
bind = SUPER+SHIFT, R,       togglegaps
