#custom app bind
# menu and terminal
bind=SUPER,space,spawn,qs -c noctalia-shell ipc call launcher toggle
bind=SUPER+SHIFT,Escape,spawn,qs -c noctalia-shell ipc call sessionMenu toggle
bind=SUPER,Return,spawn,kitty fish

bind=SUPER,b,spawn,google-chrome-stable
