#####################
### MISCELLANEOUS ###
#####################

# Apps
bind = SUPER,       b,      spawn, google-chrome-stable
bind = SUPER+SHIFt, B,      spawn, firefox
bind = SUPER,       E,      spawn, nautilus
bind = SUPER,       Return, spawn, kitty fish
bind = SUPER+SHIFT, Return, spawn, kitty --class="terminal-flotante" fish

# Noctalia
bind=SUPER,       space,  spawn, qs -c noctalia-shell ipc call launcher toggle
# bind=SUPER SHiFT, L,      spawn, qs -c noctalia-shell ipc call lockScreen lock
bind=SUPER+SHIFT, Escape, spawn, qs -c noctalia-shell ipc call sessionMenu toggle

bind=SUPER,       N, spawn, qs -c noctalia-shell ipc call notifications toggleHistory
bind=SUPER SHIFT, N, spawn, qs -c noctalia-shell ipc call notifications clear

bind=SUPER+SHIFT, C, spawn, qs -c noctalia-shell ipc call controlCenter toggle
bind=SUPER+CTRL,  C, spawn, qs -c noctalia-shell ipc call calendar toggle

bind=SUPER,       W, spawn, qs -c noctalia-shell ipc call wallpaper toggle
bind=SUPER+SHIFT, W, spawn, qs -c noctalia-shell ipc call wallpaper random all

bind=SUPER, Z, spawn, qs -c noctalia-shell ipc call idleInhibidor toggle
bind=SUPER, X, spawn, qs -c noctalia-shell ipc call bar toggle
