##############
### SYSTEM ###
##############

# reload config
bind = SUPER+CTRL, R, reload_config

# exit
bind = SUPER+CTRL, Escape, quit

# Toggle
bind = SUPER,       Escape, toggleoverview
bind = SUPER+SHIFT, G,      toggleoverlay
