#########################
### WINDOW MANAGEMENT ###
#########################

# Maximize
bind = SUPER,       M, togglemaximizescreen
bind = SUPER+SHIFT, M, togglefullscreen
bind = SUPER+CTRL,  M, togglefakefullscreen

# Minimize
bind = SUPER,       O, minimized,
bind = SUPER+SHIFT, O, restore_minimized
bind = SUPER,       Z, toggle_scratchpad

# Floating
bind = SUPER, F, togglefloating
bind = SUPER, C, centerwin

#General
bind = SUPER, Q, killclient,
bind = SUPER, G, toggleglobal,
