id         = "alexander6432/hyprlayout"
name       = "Hyprlayout"
version    = "0.1"
plugin_api = 3
author     = "alexander6432"
license = "MIT"
dependencies = []
tags = ["Hyprland"]
icon = "puzzle"
description = "Ver que tipo de layout estas usando"

[[widget]]
id    = "hyprlayout"
entry = "widget.luau"
