color0 #291914
color1 #ee4103
color2 #fd7d4f
color3 #fccd36
color4 #c8fc36
color5 #fea281
color6 #fde081
color7 #f3f2f2
color8 #74645f
color9 #ee4103
color10 #fd7d4f
color11 #fccd36
color12 #c8fc36
color13 #fea281
color14 #fde081
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #291914
background            #291914
foreground            #f3f2f2
selection_foreground  #b6b1af
selection_background  #37221b
active_border_color   #fd7d4f
inactive_border_color #37221b
url_color             #fd7d4f
