###############
### MANGOWM ###
###############

source = ~/.config/mango/mango/key_bindings.conf
source = ~/.config/mango/mango/configuration/autostart.conf
source = ~/.config/mango/mango/configuration/input.conf
source = ~/.config/mango/mango/configuration/miscellaneous.conf
source = ~/.config/mango/mango/configuration/monitors.conf
source = ~/.config/mango/mango/visuals/animations.conf
source = ~/.config/mango/mango/visuals/theming.conf
source = ~/.config/mango/mango/visuals/window_effects.conf
source = ~/.config/mango/mango/window_management/layouts.conf
source = ~/.config/mango/mango/window_management/overview.conf
source = ~/.config/mango/mango/window_management/rules.conf
source = ~/.config/mango/mango/window_management/scratchpad.conf

# This sources the noctalia theme
source = /home/alex/.config/mango/noctalia.conf
