##################
### ANIMATIONS ###
##################

# https://wiki.hypr.land/Configuring/Variables/#animations
animations {
    enabled = yes, please :)

    # Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
    #        NAME,           X0,   Y0,   X1,   Y1
    bezier = linear,         0,    0,    1,    1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = easeOutCubic,   0.33, 1,    0.68, 1
    bezier = easeInCubic,    0.32, 0,    0.67, 0

    # Default animations, see https://wiki.hypr.land/Configuring/Animations/
    #                       NAME,            ONOFF, SPEED, CURVE,       [STYLE]
    animation =             global,              1, 10,   default

        animation =         windows,             1, 2.0, easeInCubic
            animation =     windowsIn,           1, 4.0, easeOutCubic, slide bottom
            animation =     windowsOut,          1, 2.0, easeInCubic,  slide top
            animation =     windowsMove,         1, 4.0, easeOutCubic

        animation =         layers,              1, 2.0, easeInCubic
            animation =     layersIn,            1, 4.0, easeOutCubic, popin 75%
            animation =     layersOut,           1, 2.0, easeInCubic,  popin 75%

        animation =         fade,                1, 2.0, easeInCubic
            animation =     fadeIn,              1, 4.0, easeOutCubic
            animation =     fadeOut,             1, 4.0, easeInCubic
            animation =     fadeSwitch,          1, 4.0, easeInOutCubic
            animation =     fadeShadow,          1, 4.0, easeInOutCubic
            animation =     fadeDim,             1, 4.0, easeInOutCubic
            animation =     fadeLayers,          1, 2.0, easeInCubic
                animation = fadeLayersIn,        1, 4.0, easeOutCubic
                animation = fadeLayersOut,       1, 2.0, easeInCubic
            animation =     fadePopups,          1, 2.0, easeInCubic
                animation = fadePopupsIn,        1, 4.0, easeOutCubic
                animation = fadePopupsOut,       1, 2.0, easeInCubic
            animation =     fadeDpms,            1, 4.0, easeInOutCubic

        animation =         border,              1, 4.0, easeInOutCubic
        animation =         borderangle,         1, 120, easeInOutCubic

        animation =         workspaces,          1, 2.0, easeInCubic,  fade
            animation =     workspacesIn,        1, 4.0, easeOutCubic, slidefadevert
            animation =     workspacesOut,       1, 2.0, easeInCubic,  slidefadevert
            animation =     specialWorkspace,    1, 2.0, easeInCubic,  fade
                animation = specialWorkspaceIn,  1, 4.0, easeOutCubic, fade
                animation = specialWorkspaceOut, 1, 2.0, easeInCubic,  fade

        animation =         zoomFactor,          1, 8.0, easeInOutCubic
        animation =         monitorAdded,        1, 10,  easeOutCubic
}
