###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$chrome   = google-chrome-stable
$firefox  = firefox
$terminal = kitty fish

$salir = command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit

$borrar_notificaciones = qs -c noctalia-shell ipc call notifications clear
$centro_notificaciones = qs -c noctalia-shell ipc call notifications toggleHistory
$centro_control        = qs -c noctalia-shell ipc call controlCenter toggle
$bloquear_pantalla     = qs -c noctalia-shell ipc call lockScreen lock
$idle_inhibidor        = qs -c noctalia-shell ipc call idleInhibitor toggle
$menu                  = qs -c noctalia-shell ipc call launcher toggle
$power_menu            = qs -c noctalia-shell ipc call sessionMenu toggle
$toggle_bar            = qs -c noctalia-shell ipc call bar toggle
$wallpaper_random      = qs -c noctalia-shell ipc call wallpaper random all
$wallpaper_selector    = qs -c noctalia-shell ipc call wallpaper toggle

$subir_volumen =        qs -c noctalia-shell ipc call volume increase
$bajar_volumen =        qs -c noctalia-shell ipc call volume decrease
$silenciar_volumen =    qs -c noctalia-shell ipc call volume muteOutput
$silenciar_microfono =  qs -c noctalia-shell ipc call volume muteInput
$subir_brillo =         qs -c noctalia-shell ipc call brightness increase
$bajar_brillo =         qs -c noctalia-shell ipc call brightness decrease
$pausar_reproducir =    qs -c noctalia-shell ipc call media playPause
$detener_reproduccion = qs -c noctalia-shell ipc call media stop
$anterior_pista =       qs -c noctalia-shell ipc call media previous
$siguiente_pista =      qs -c noctalia-shell ipc call media next
