##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = ventanas-foltantes-sin-bordes
    match:float = true
    rounding = 0
}

windowrule {
    name = firefox-video
    match:class = ^(firefox)$
    match:title = ^(Picture-in-Picture)$
    float = true
    pin = true
    opaque = true
    rounding = 4
    size = (monitor_w*0.3) (monitor_h*0.3)
    move = ((monitor_w*0.7)-10) (40)
}

windowrule {
    name = chrome-video
    match:class = ^$
    match:title = ^(Pantalla en pantalla)$
    float = true
    pin = true
    opaque = true
    rounding = 4
    size = (monitor_w*0.3) (monitor_h*0.3)
    move = ((monitor_w*0.7)-10) (40)
}

windowrule {
    name = telegram-video
    match:class = ^(org.telegram.desktop)$
    match:title = ^(Visor multimedia)$
    float = true
    pin = true
    opaque = true
    rounding = 4
    size = (monitor_w*0.37) (monitor_h*0.48)
    move = ((monitor_w*0.63)-10) (40)
}

layerrule {
  name = noctalia
  match:namespace = noctalia-background-.*$
  ignore_alpha = 0.5
  blur = true
  blur_popups = true
}
