# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

source=~/.config/mango/mango/bindings/floating_window_management.conf
source=~/.config/mango/mango/bindings/focus_movement.conf
source=~/.config/mango/mango/bindings/hardware.conf
source=~/.config/mango/mango/bindings/layouts.conf
source=~/.config/mango/mango/bindings/miscellaneous.conf
source=~/.config/mango/mango/bindings/system.conf
source=~/.config/mango/mango/bindings/tags.conf
source=~/.config/mango/mango/bindings/window_management.conf
