# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

source=~/.config/mango/mango/binds/floating_window_management.conf
source=~/.config/mango/mango/binds/focus_movement.conf
source=~/.config/mango/mango/binds/hardware.conf
source=~/.config/mango/mango/binds/layouts.conf
source=~/.config/mango/mango/binds/system.conf
source=~/.config/mango/mango/binds/tags.conf
source=~/.config/mango/mango/binds/window_management.conf

#custom app bind
bind=SUPER,Return,spawn,google-chrome
bind=CTRL+SUPER,Return,spawn,foot -e yazi
bind=CTRL+ALT,a,spawn_shell,grim -g "$(slurp -b '#2E2A1E55' -c '#fb751bff')" -t ppm - | satty -f -
bind=SUPER,h,spawn,bash ~/.config/mango/scripts/hide_waybar_mango.sh
bind=SUPER,l,spawn,swaylock -f -c 000000
bind=CTRL+ALT,backslash,spawn,swaync-client -t
bind=CTRL+ALT,BackSpace,spawn,swaync-client -C
bind=SUPER,p,spawn,bash ~/.config/mango/scripts/monitor.sh
bind=SUPER+SHIFT,p,spawn,bash ~/.config/mango/scripts/virmon.sh

# menu and terminal
bind=SUPER,space,spawn,qs -c noctalia-shell ipc call launcher toggle
bind=SUPER,Return,spawn,kitty fish

bind=SUPER+SHIFT,Escape,spawn,qs -c noctalia-shell ipc call sessionMenu toggle

# Mouse Button Bindings
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=alt,btn_middle,set_proportion,0.5
mousebind=SUPER,btn_right,moveresize,curresize
mousebind=SUPER+CTRL,btn_left,minimized
mousebind=SUPER+CTRL,btn_right,killclient
mousebind=SUPER+CTRL,btn_middle,togglefullscreen
mousebind=NONE,btn_middle,togglemaximizescreen,0

# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
axisbind=alt,UP,focusdir,left
axisbind=alt,DOWN,focusdir,right
axisbind=shift+super,UP,exchange_client,left
axisbind=shift+super,DOWN,exchange_client,right

# Gesturebind
gesturebind=none,left,3,focusdir,left
gesturebind=none,right,3,focusdir,right
gesturebind=none,up,3,focusdir,up
gesturebind=none,down,3,focusdir,down
gesturebind=none,left,4,viewtoleft_have_client
gesturebind=none,right,4,viewtoright_have_client
gesturebind=none,up,4,toggleoverview,1
gesturebind=none,down,4,toggleoverview,1

# namescrtachpad
# bind=ctrl+super,h,toggle_named_scratchpad,st-yazi,none,st -c st-yazi -e yazi
# windowrule=isnamedscratchpad:1,width:1280,height:800,appid:st-yazi
