####################
### Key Bindings ###
####################

source = ~/.config/mango/mango/key_bindings/floating_window_management.conf
source = ~/.config/mango/mango/key_bindings/focus_movement.conf
source = ~/.config/mango/mango/key_bindings/hardware.conf
source = ~/.config/mango/mango/key_bindings/layouts.conf
source = ~/.config/mango/mango/key_bindings/miscellaneous.conf
source = ~/.config/mango/mango/key_bindings/system.conf
source = ~/.config/mango/mango/key_bindings/tags.conf
source = ~/.config/mango/mango/key_bindings/window_management.conf
